
export const SET_IS_FIRST_TIME_LOGIN = 'SET_IS_FIRST_TIME_LOGIN';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const RESET_STORE = 'RESET_STORE';
export const RESET_AUTHENTICATION_FAILURE = 'RESET_AUTHENTICATION_FAILURE';
export const CLEAR_SERVER_FORM_ERROR = 'CLEAR_SERVER_FORM_ERROR';
