
export const SET_USER_INFO = 'SET_USER_INFO';
export const USER_PREFERENCES_SUCCESS = 'USER_PREFERENCES_SUCCESS';
export const USER_PREFERENCES_FAILURE = 'USER_PREFERENCES_FAILURE';
export const USER_PREFERENCES_UPDATE_SUCCESS =
  'USER_PREFERENCES_UPDATE_SUCCESS';
export const USER_PREFERENCES_UPDATE_FAILURE =
  'USER_PREFERENCES_UPDATE_FAILURE';
export const CURRENT_USER_PERMISSION_SUCCESS =
  'CURRENT_USER_PERMISSION_SUCCESS';
