
export const RESPONSE_MSG = {
  ECONNABORTED: 'ECONNABORTED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  CONNECTION_OPENED: 'CONNECTION OPENED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
};
export const RESPONSE_CODE = {
  SUCCESS: 200,
  SUCCESSFUL: 299,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};
